---
title: "Draft Présentation Articles"
author: Corentin DUCLOUX
header-includes:
    - \usepackage{xcolor}
    - \usepackage{color}
    - \usepackage[T1]{fontenc}
    - \usepackage{lmodern}
    - \usepackage[most]{tcolorbox}
    - \definecolor{StackOgray}{HTML}{e3e6e8}
output:
    pdf_document:
        toc: TRUE
---

\newcommand{\code}[1]{\colorbox{StackOgray}{\texttt{#1}}}

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)
```


## `Running Shoes in Spain`: *Arrrondo et Al*

But de l'article : **déterminer les composantes principales des prix des sneakers en Espagne**

L'article a été cité **15** fois mais pas dans un contexte de réplication de la méthodologie appliquée ici.

*Innovation* : Utilisation d'un modèle SFA & de pricing Hedonic $\Rightarrow$ possibilité d'inclure la notion de produit innefficient (trop cher). Cette méthodologie peut être appliquée dans d'autres axes : smartphones, voitures, etc.

- Produit = décomposition en bundle d'attributs ~ cf `Kevin Lancaster`

- Les vendeurs combinent un grand nombre d'attributs dans leurs biens pour pouvoir se différencier des entreprises concurrentes. Le but est que les acheteurs se focalisent sur ces attributs pour faire le choix de leur produit préféré.

- Les sneakers sont des biens hautement différenciés : elles se vendent à des prix qui varient selon une marge très vaste.

- La méthode de pricing hédonique estime que la différence de prix des sneakers est due à ses caractéristiques.

- En estimant l'efficacité des produits, le papier pointe les produits overprice pour prédire le montant des réductions à leur accorder afin d'atteindre la frontière compétitive pour ces produits.

- Les sneakers sont des `biens d'expérience` dont la qualité et la correspondance aux attentes ne peut être évaluée qu'après leur utilisation. Dès lors, pour effectuer un choix rationnel, les consos s'orientent vers des recommandations d'amateurs & experts sur des caractéristiques comme : *response*, *stability*, *duration* et *flexibility*.

***

Les attributs objectifs mesurables constituent la base des modèles de Pricing Hédonique. Cependant, dans ces modèles, le prix d’un produit donné peut ne pas refléter pleinement la valeur totale de ses attributs mesurables. 

Chaque produit spécifique est unique et possède certaines caractéristiques qui ne peuvent pas être mesurées objectivement. Certains clients peuvent être disposés à payer un prix plus élevé que le prix qui serait raisonnable selon l'ensemble des attributs objectifs, simplement parce que le produit offre un statut accru au client ou est considéré comme plus fiable ou de meilleure qualité. 

L’inclusion de variables dummies pour les marques dans la spécification du modèle hédonique permet de contrôler ces effets. Mais il existe également des variations aléatoires qui peuvent être associées à la conception spécifique des produits, qui ne peuvent être mesurées et contrôlées objectivement. 

Enfin, certains produits peuvent également être trop chers par rapport aux caractéristiques objectives proposées et à la valeur de la marque, simplement parce que le prix en vigueur n'est pas le bon prix.

Le modèle proposé envisage toutes ces possibilités.

### Hypothèses

1. Les réductions de prix seront d'autant plus grandes que les produits sont inefficaces selon le modèle, toutes choses égales par ailleurs, indépendamment de la marque.

2. Les évaluations des experts sont positivement corrélées avec l'efficacité des produits.

### Modèle

Modèle Semi-Log (Log-Linéaire) : la variable dépendante est prise en logarithme alors que les variables
explicatives sont linéaires. L'utilisation d'une forme fonctionnelle inappropriée pourrait résulter dans des conclusions faussées et la forme semi-log semble être la plus appropriée. $\Rightarrow$ (Voir Ajide Kazeem Bello and Alabi Moruf, 2010)

*Avantage* : les coefficients $\beta$ peuvent être interprétés comme des semiélasticités $\Rightarrow$ le rapport entre une variation en différence des variables dépendantes et une variation relative (en %) de la variable indépendante.

Autrement dit, plus les coefficients associés sont grands, plus leur impact sur le prix sera important.

$$Log(P_{ik})=\alpha_k+\beta X_{ik}+e_{ik}$$

- $\alpha_k=$ Effet de la marque $k$ sur le prix du produit (*dummies*)
- $\beta=$ Vecteur des coefficients associés aux attributs du produit
- $X_{ik}=$ Vecteur des attributs d'un produit d'une marque $k$
- $e_{ik}=$ Erreur aléatoire

> Dans ce modèle de base, on ne peut pas encore déterminer si des produits sont overprice (innefficients) !

**Prise en compte de la frontière stochastique:**

- Erreur composite $\epsilon_{ik}= (u_{ik} + v_{ik})$  avec $v_{ik}$ normalement distribué et $u_{ik}$ un composant unilatéral.

- $u_{ik}$ sont distribués indépendamment de $v_{ik}$

> L'index d'efficacité d'un produit est $\theta_{ik} = e^{-u_{ik}} \in (0,1]$

- Un $u_{ik}$ grand signifie que le prix fixé est très au dessus de la frontière optimale, dès lors, le produit sera d'autant plus inefficace et l'index proche de 0. Un $u_{ik}$ proche ou $=0$ indique que le produit est proche de la frontière optimale de pricing.

- Index d'efficacité moyen toutes sneakers confondues = 0.85 donc les sneakers sont 15% overprice en moyenne.

### Résultats 

#### Index d'efficacité

| **Brand**             | **Average** |
| --------------------- | ------- |
| Adidas ($n=$ 28)      | 0.832   |
| Asics ($n=$ 35)       | 0.864   |
| Saucony ($n=$ 15)     | 0.875   |
| Nike ($n=$ 25)        | 0.824   |
| Brooks ($n=$ 16)      | 0.860   |
| Mizuno ($n=$ 29)      | 0.858   |
| New Balance ($n=$ 18) | 0.848   |
| Reebok ($n=$ 5)       | 0.859   |

#### Coefficients : régression hédonique

|                 | Coef. | $t$       |
| --------------- | ----------- | ------- |
| Lightness       | 0.007       | 0.24    |
| Cushioning      | 0.064       | 2.54 **  |
| Flexibility     | 0.058       | 2.17 **  |
| Response        | 0.050       | 1.65 *   |
| Stability       | 0.070       | 2.74 *** |
| Grip            | -0.045      | -1.59   |
| \code{Brand dummies} |             |         |
| Adidas          | 2.697       | 6.71 *** |
| Asics           | 2.679       | 6.88 *** |
| Saucony         | 2.779       | 6.89 *** |
| Nike            | 2.714       | 6.43 *** |
| Brooks          | 2.834       | 7.01 *** |
| Mizuno          | 2.524       | 6.36 *** |
| New Balance     | 2.544       | 6.21 *** |
| Reebok          | 2.522       | 6.26 *** |

- Toutes les caractéristiques ne sont pas significatives dans la régression, par exemple : Grip & Lightness n'influent pas sur le prix car les coefficients associés ne sont pas statistiquement significatifs.

- De manière plus intéressante, les dummies de marques sont elles toutes significatives au seuil de 1%, et ce sont elles qui "drivent" le prix dans une importance beaucoup plus grande que les caractéristiques associés aux chaussures.

#### Régression estimant la relation entre la réduction de prix et la product efficiency

| **Efficiency** | **Coefficient** | **SD** | **$t$**    |
|----------------|-----------------|--------|----------|
|                | -0.520         | 0.116  | -4.47 *** |
| \code{Brand dummies}  |                 |        |          |
| Adidas         | 0.523           | 0.099  | 5.23 ***  |
| Asics          | 0.505           | 0.103  | 4.90 ***  |
| Saucony        | 0.569           | 0.107  | 5.30 ***  |
| Nike           | 0.446           | 0.099  | 4.50 ***  |
| Brooks         | 0.465           | 0.105  | 4.42 ***  |
| Mizuno         | 0.483           | 0.103  | 4.70 ***  |
| New Balance    | 0.504           | 0.103  | 4.88 ***  |
| Reebok         | 0.469           | 0.115  | 4.06 ***  |

*Note* : 2 périodes de récolte $\Rightarrow$ Février & Juin - 4 mois d'intervalle entre les deux dates. 

- Ces résultats confirment la relation inverse entre l’efficacité du produit et la baisse des prix. 

- La relation négative est statistiquement significative au seuil de 1%. 

- Par conséquent, plus l’efficacité du produit est élevée, plus la réduction de prix est faible en seconde période. (On peut aussi voir l'effet grâce aux dummies $\Rightarrow$ les marques avec une efficacité moyenne plus grande ont un coef supérieur et donc leur réduction de prix sera moins importante)

- Le résultat donne des indications sur la manière dont les réductions de prix se dérouleront sur le marché, compte tenu de l’estimation de l’efficacité du produit issue de la comparaison initiale du marché. 

- Une augmentation de 1 % du surprix d’un produit (une réduction de 1 % de l’efficacité du produit) entraînerait une réduction d’environ 0,5 % du prix du produit dans les quatre mois suivants. 

- Avec un indice d'efficacité de 0.54, le modèle Nike qui affichait un prix de 190 euros en février aurait dû baisser son prix d'environ 23 % $\Rightarrow$ réduction réelle des prix a été supérieure = 27,8 %.

#### Régression des évaluations des experts vs product efficiency

|               | **Coefficient** | **SD** | **t**    |
|---------------|-----------------|--------|----------|
| Efficiency    | 0.279           | 0.031  | 8.85***  |
| \code{Brand dummies} |                 |        |          |
| Adidas        | -0.139          | 0.027  | -5.14*** |
| Asics         | -0.145          | 0.028  | -5.22*** |
| Saucony       | -0.162          | 0.027  | -5.85*** |
| Nike          | -0.150          | 0.028  | -5.34*** |
| Brooks        | -0.171          | 0.029  | -5.91*** |
| Mizuno        | -0.119          | 0.028  | -4.20*** |
| New Balance   | -0.135          | 0.028  | -4.71*** |
| Reebok        | -0.128          | 0.028  | -4.58*** |

- Cela signifie que plus l'efficacité du produit est élevée (c'est-à-dire plus son surprix est faible), plus l'évaluation globale de l'expert est élevée. 

- Autrement dit, les évaluations d'experts peuvent être considérées comme des indicateurs fiables de l'efficacité des produits, basés sur une comparaison des prix, des marques et des caractéristiques techniques. En combinant les hypothèses 1 et 2, nous pouvons également nous attendre à ce que les évaluations d’experts soient un bon indicateur des futures remises sur les achats en ligne. 

- Une bonne évaluation par un expert est un indicateur crédible du juste prix pour le modèle de chaussure et, par conséquent, les acheteurs ne doivent pas s'attendre à des remises importantes à court terme.

### Confirmation Hypothèses

- Confirmation $H_1$ : Relation inverse entre l'efficacité du produit et la réduction de prix. La réduction de prix est donc d'autant plus grande que la sneakers est overprice !

- Le modèle permet une bonne prédiction des réductions de prix pour rendre compétitifs les sneakers overprice !

## `A New Approach To Consumer Theory`: *Kevin Lancaster*

**But du modèle proposé : remplacer l'approche traditionnelle par une approche pratique et plus proche du comportement des consommateurs**

- **L'approche traditionnelle de la théorie du consommateur en microéconomie** : les consommateurs préfèrent certains biens et ces préférences vont permettre de construire leur fonction d'utilité $u(x)$ qu'ils vont chercher à maximiser. Dans ce cas, les biens sont consommés parce qu'ils procurent de l'utilité. 
  - *Exemple* : Un ordinateur peut fournir de l'utilité à un conso, quand un autre peut lui préférer une voiture.

- **Nouvelle approche** : Cette fois, ce ne sont pas les biens eux-mêmes qui procurent de l'utilité, mais les caractéristiques des biens. Les biens sont des *inputs* et ce sont les caractéristiques de ces biens qui sont des *outputs*. En général, même uun bien "seul" possède plus d'une caractéristique.
  - *Exemple* : Ce n'est pas le fait de posséder un ordinateur qui procure de l'utilité à un consommateur, mais le fait de pouvoir naviguer sur internet, programmer, jouer, etc.

- L'ajout d'un nouveau bien dans ce modèle est très simple : si un nouveau bien possède des caractéristiques dans les mêmes niveaux de proportions qu'un ancien bien, alors : 

    $\Rightarrow$ A) Il ne sera pas vendu si son prix est trop cher. 

    $\Rightarrow$ B) Il remplacera l'ancien bien si son prix est suffisamment compétitif.

## `SFA BOOK`: *Kumbhakar*

- L'**efficacité technique** peut soit être modélisée comme *output-orientée* ou *input-orientée*
- On se concentre sur l'efficacité technique output-orientée

Dans ce cas, un modèle de frontière de production stochastique avec efficacité technique output-orientée peut s'écrire :

> $(1)$ - $\text{ln } y_i = \text{ln }y_i^*-u_i, \text{ } u_i\geq0$ 

> $(2)$ - avec $\text{ln }y_i^* = f(x_i;\beta) + v_i$

- $i$ sont ici les observations (entreprises, individus,etc.)
- $y_i=$ output observé
- $y_i^*=$ output maximum
- $x_i= J\times 1$ vecteur des inputs variables
- $\beta= J\times 1$ vecteur des coefficients associés aux input variables
- $v_i=$ est une erreur aléatoire $\Rightarrow$ variation inexpliquée par les variables indépendantes du modèle $-$ cette erreur n'a pas de biais et peut être positive comme négative d'où le $E(v_i)=0$, la valeur attendue de ces erreurs sur un grand nombre d'observations est donc égal à 0.
- $u_i=$ innefficacité productive $\geq$ 0 $\Leftrightarrow u_i = \ln y_i^* - \ln y_i$ $-$ *en réarrangeant l'équation $(1)$*. $u_i$ correspond donc à la log-différence entre l'output réel et l'output maximum. **Dès lors, $u_i \times 100 \%$ donne le pourcentage d'output perdu à cause de l'innefficacité technique.**

L'équation $(2)$ définit la fonction de la frontière stochastique de production. Étant donné $x$, la frontière donne le niveau de production maximum possible et est stochastique à cause de $v_i \Rightarrow$ 
« stochastique » fait référence à l'inclusion du caractère aléatoire ou de la variabilité non observée dans le modèle pour tenir compte de facteurs qui affectent la production ou la rentabilité mais qui ne sont pas directement observables.

- Puisque $u_i \geq 0$, l'output observé $y_i$ est limité en dessous du niveau de production frontière $y_i^*$

> Etant donné l'équation $(1)$ et $(2)$, on peut ré-écrire le modèle de cette façon :

$$
\begin{cases}
\ln y_i = \ln y_i^* - u_i\\
\ln y_i^* = f(x_i, \beta) + v_i
\end{cases}
$$

- On substitue alors $\ln y_i^*$ dans l'équation $(1)$ et on trouve :

$$\ln y_i = f(x_i, \beta) - u_i + v_i$$
$$\ln y_i = f(x_i, \beta) + \epsilon_i$$

- Avec le terme d'erreur composé $\epsilon_i = v_i - u_i$

> En réarrangeant l'équation $(1)$ :

$$
\ln y_i = \ln y_i^* - u_i\\
\Leftrightarrow \ln y_i - \ln y_i^* = -u_i\\
\Leftrightarrow \ln \left(\frac{y_i}{y_i^*}\right)= -u_i\\
\Leftrightarrow \exp \ln \left(\frac{y_i}{y_i^*}\right)= \exp(-u_i)\\
\Leftrightarrow  \frac{y_i}{y_i^*}= \exp(-u_i)\\
\Leftrightarrow \boxed{\exp(-u_i) = \frac{y_i}{y_i^*}}\\
$$

- On voit ici que $\exp(-u_i)$ donne le ratio d'output produit sur l'output maximum possible. Le ratio se réfère à l'efficacité technique de la firme $i$.

## Rosen 

*Equation de prix hédonique standard* :

$$P_h = h(z) + v$$

- avec $P_h$ le prix hédonique (ou le logarithme du prix hédonique)
- avec $z$ un vecteur de
caractéristiques du produit influençant la valeur globale du bien sur le marché
- avec $v$ représentant le bruit aléatoire et l'erreur de mesure dans le prix

**Cette fonction de prix hédonique $(1)$ correspond au modèle de full-information développé par Rosen (1974)**